In [88]:
import pandas as pd
df = pd.read_csv('data/가구 행정동별 생활금융 통계.csv',encoding = 'cp949')
df.head(3)

,데이터_기준월(BS_YR_MON),통계청_행정동코드(HANG_CD),행안부_행정동코드(G_ADM_DONG_CD),집계가구수(STAT_H_DONG_001),가구주가_남성인_가구수(STAT_H_DONG_002),가구주가_여성인_가구수(STAT_H_DONG_003),가구주연령대가_20대인_가구수(STAT_H_DONG_004),가구주연령대가_30대인_가구수(STAT_H_DONG_005),가구주연령대가_40대인_가구수(STAT_H_DONG_006),가구주연령대가_50대인_가구수(STAT_H_DONG_007),...,2인가구평균월소비(STAT_H_DONG_060),3인가구평균월소비(STAT_H_DONG_061),4인가구평균월소비(STAT_H_DONG_062),5인이상가구평균월소비(STAT_H_DONG_063),평균대출잔액(STAT_H_DONG_064),1인가구평균대출잔액(STAT_H_DONG_065),2인가구평균대출잔액(STAT_H_DONG_066),3인가구평균대출잔액(STAT_H_DONG_067),4인가구평균대출잔액(STAT_H_DONG_068),5인이상가구평균대출잔액(STAT_H_DONG_069)
0,202004,1111076,11215847,6617,3644,2281,174,1144,325,2279,...,244.1,451.5,1005.8,579.5,5252.1,3351.3,7699.6,6487.5,14987.8,17407.7
1,202004,1106083,11380520,11073,2559,4277,610,534,2454,1249,...,333.1,544.5,489.9,1852.0,4435.8,9503.1,3189.5,8524.2,24009.7,9576.4
2,202002,1111064,11740650,8225,3155,5144,1527,2732,1605,2761,...,263.0,676.7,1056.6,903.1,4074.8,3678.0,11737.5,4888.3,26690.9,13926.0

In [89]:
# 년월 분리
df['데이터_기준월(BS_YR_MON)'] = df['데이터_기준월(BS_YR_MON)'].astype(str)
df['통계청_행정동코드(HANG_CD)'] = df['통계청_행정동코드(HANG_CD)'].astype(str)
df['행안부_행정동코드(G_ADM_DONG_CD)'] = df['행안부_행정동코드(G_ADM_DONG_CD)'].astype(str)
df['기준연도'] = df['데이터_기준월(BS_YR_MON)'].map(lambda x:x[:4])
df['기준월'] = df['데이터_기준월(BS_YR_MON)'].map(lambda x:x[4:])

In [119]:
저소득=df[['집계가구수(STAT_H_DONG_001)','1분위소득가구수(STAT_H_DONG_018)','2분위소득가구수(STAT_H_DONG_019)','3분위소득가구수(STAT_H_DONG_020)','4분위소득가구수(STAT_H_DONG_021)','5분위소득가구수(STAT_H_DONG_022)']]

In [102]:
저소득.sum()

데이터_기준월(BS_YR_MON)           2020042020042020022019112019082019052019062019...
통계청_행정동코드(HANG_CD)           1111076110608311110641117061111205711190711107...
행안부_행정동코드(G_ADM_DONG_CD)     1121584711380520117406501174061011560535112906...
집계가구수(STAT_H_DONG_001)                                                  244602
1분위소득가구수(STAT_H_DONG_018)                                                47891
2분위소득가구수(STAT_H_DONG_019)                                                46783
3분위소득가구수(STAT_H_DONG_020)                                                47165
4분위소득가구수(STAT_H_DONG_021)                                                49533
5분위소득가구수(STAT_H_DONG_022)                                                40579
dtype: object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   데이터_기준월(BS_YR_MON)         30 non-null     object
 1   통계청_행정동코드(HANG_CD)         30 non-null     object
 2   행안부_행정동코드(G_ADM_DONG_CD)   30 non-null     object
 3   1분위소득가구수(STAT_H_DONG_018)  30 non-null     int64
 4   2분위소득가구수(STAT_H_DONG_019)  30 non-null     int64
 5   3분위소득가구수(STAT_H_DONG_020)  30 non-null     int64
 6   4분위소득가구수(STAT_H_DONG_021)  30 non-null     int64
dtypes: int64(4), object(3)
memory usage: 1.8+ KB

In [98]:
StandardScaler().fit_transform(저소득.groupby(['데이터_기준월(BS_YR_MON)','통계청_행정동코드(HANG_CD)','행안부_행정동코드(G_ADM_DONG_CD)']).mean())

array([[ 1.04788062,  1.51130691, -1.68130389, -0.54529358, -0.78872808,
        -1.16585081],
       [ 3.0754821 ,  0.36123797,  0.04024781, -0.26341874, -0.14592927,
        -0.38212632],
       [ 0.19470368, -0.18004586,  0.09833319,  0.8410704 ,  0.6528148 ,
        -0.21062163],
       [-0.12047627,  2.0882518 , -1.34515022, -0.06783212,  0.3713526 ,
         1.14166692],
       [-0.09654282, -0.43222045, -0.46892613, -0.08221349,  1.38436294,
        -0.44449167],
       [ 0.1016666 , -0.37872887,  0.94860423,  0.72314317, -0.44260564,
         0.23840885],
       [ 0.00391025,  1.15342278,  0.45920404,  0.56926253, -0.79126377,
         3.05108587],
       [-0.15148863, -0.63217706,  0.0044079 , -1.62101998,  0.43854853,
        -0.96836056],
       [ 0.6875305 , -1.27407601,  0.41347725, -0.85305487, -0.18776825,
         0.65105955],
       [-0.29306679, -0.69203669,  2.51938113, -0.74807088,  0.14060431,
         2.16861625],
       [-1.85312325, -0.70604639,  0.16383372,  0.98056968, -0.90537007,
        -1.14818063],
       [ 1.31856458,  0.21859376,  0.34179743, -1.29024849,  0.40431664,
        -0.42474264],
       [ 0.4040371 , -0.82449202, -0.76182473,  1.82044163,  0.24837137,
        -0.74904243],
       [-0.6133031 ,  0.33449218,  0.26270245, -2.05533733,  1.33364903,
         0.18435889],
       [ 0.02413571, -1.32374676,  0.07485186, -0.48201555, -1.60395417,
        -0.51621181],
       [-1.00803648,  0.40199346, -1.30807445,  0.71595249,  3.1390642 ,
        -0.12331014],
       [ 0.98417045,  0.46822113, -0.47263371, -1.59369538,  0.63252923,
         0.2685521 ],
       [-0.51790639,  1.72909405,  0.74097991, -0.31662981, -0.33864213,
        -0.71785976],
       [-1.62154184, -1.08176105, -0.60857821, -0.68335472, -0.3538563 ,
        -0.63054828],
       [ 0.40808219,  0.50006135,  0.7199703 , -0.28786707, -0.12310801,
        -0.41538784],
       [ 0.08986842, -0.93784323,  1.93481978,  0.143574  , -1.91204117,
        -0.34678596],
       [-1.02421685,  0.17783827, -1.04730818,  1.20923345,  0.23442505,
         1.03356699],
       [-0.38542968, -1.30336901,  1.23408768, -0.89763712, -0.49331955,
        -0.57338004],
       [-0.35441732, -0.2424527 , -0.84586315,  0.18959438, -0.22326799,
         0.48787023],
       [ 0.13638696,  1.53168466,  0.20585293, -0.36552646,  0.74156414,
        -0.75320012],
       [-1.3538917 , -1.95545683,  0.44684545, -0.31087726,  1.33745257,
        -0.39875708],
       [ 1.52419   , -0.19150834, -0.78036262,  1.7528492 , -0.05210854,
        -0.39667824],
       [ 0.80483812,  1.50239165, -1.28953656,  0.77347797, -1.32629551,
         2.16653741],
       [-1.36838661,  0.10396895, -1.36739568,  1.54575748, -0.03055513,
        -0.76463377],
       [-0.04361956,  0.07340233,  1.36756046,  1.19916649, -1.34024184,
        -0.26155332]])

In [121]:
from sklearn.preprocessing import StandardScaler

StandardScaler().fit_transform(저소득)

array([[-0.51790639,  1.72909405,  0.74097991, -0.31662981, -0.33864213,
        -0.71785976],
       [ 0.98417045,  0.46822113, -0.47263371, -1.59369538,  0.63252923,
         0.2685521 ],
       [ 0.02413571, -1.32374676,  0.07485186, -0.48201555, -1.60395417,
        -0.51621181],
       [ 1.31856458,  0.21859376,  0.34179743, -1.29024849,  0.40431664,
        -0.42474264],
       [-0.15148863, -0.63217706,  0.0044079 , -1.62101998,  0.43854853,
        -0.96836056],
       [-0.12047627,  2.0882518 , -1.34515022, -0.06783212,  0.3713526 ,
         1.14166692],
       [ 0.1016666 , -0.37872887,  0.94860423,  0.72314317, -0.44260564,
         0.23840885],
       [ 0.6875305 , -1.27407601,  0.41347725, -0.85305487, -0.18776825,
         0.65105955],
       [ 0.08986842, -0.93784323,  1.93481978,  0.143574  , -1.91204117,
        -0.34678596],
       [-0.35441732, -0.2424527 , -0.84586315,  0.18959438, -0.22326799,
         0.48787023],
       [-0.29306679, -0.69203669,  2.51938113, -0.74807088,  0.14060431,
         2.16861625],
       [-1.85312325, -0.70604639,  0.16383372,  0.98056968, -0.90537007,
        -1.14818063],
       [ 0.4040371 , -0.82449202, -0.76182473,  1.82044163,  0.24837137,
        -0.74904243],
       [ 3.0754821 ,  0.36123797,  0.04024781, -0.26341874, -0.14592927,
        -0.38212632],
       [ 1.04788062,  1.51130691, -1.68130389, -0.54529358, -0.78872808,
        -1.16585081],
       [-0.38542968, -1.30336901,  1.23408768, -0.89763712, -0.49331955,
        -0.57338004],
       [-0.04361956,  0.07340233,  1.36756046,  1.19916649, -1.34024184,
        -0.26155332],
       [ 0.80483812,  1.50239165, -1.28953656,  0.77347797, -1.32629551,
         2.16653741],
       [ 0.13638696,  1.53168466,  0.20585293, -0.36552646,  0.74156414,
        -0.75320012],
       [-1.62154184, -1.08176105, -0.60857821, -0.68335472, -0.3538563 ,
        -0.63054828],
       [-1.00803648,  0.40199346, -1.30807445,  0.71595249,  3.1390642 ,
        -0.12331014],
       [-0.09654282, -0.43222045, -0.46892613, -0.08221349,  1.38436294,
        -0.44449167],
       [-1.36838661,  0.10396895, -1.36739568,  1.54575748, -0.03055513,
        -0.76463377],
       [ 0.00391025,  1.15342278,  0.45920404,  0.56926253, -0.79126377,
         3.05108587],
       [ 0.19470368, -0.18004586,  0.09833319,  0.8410704 ,  0.6528148 ,
        -0.21062163],
       [-0.6133031 ,  0.33449218,  0.26270245, -2.05533733,  1.33364903,
         0.18435889],
       [-1.02421685,  0.17783827, -1.04730818,  1.20923345,  0.23442505,
         1.03356699],
       [ 1.52419   , -0.19150834, -0.78036262,  1.7528492 , -0.05210854,
        -0.39667824],
       [-1.3538917 , -1.95545683,  0.44684545, -0.31087726,  1.33745257,
        -0.39875708],
       [ 0.40808219,  0.50006135,  0.7199703 , -0.28786707, -0.12310801,
        -0.41538784]])

In [ ]:
df = pd.read_excel('data/통계청_한국행정구역분류_2022.10.1.xlsx')

In [123]:
저소득.head(3)

,집계가구수(STAT_H_DONG_001),1분위소득가구수(STAT_H_DONG_018),2분위소득가구수(STAT_H_DONG_019),3분위소득가구수(STAT_H_DONG_020),4분위소득가구수(STAT_H_DONG_021),5분위소득가구수(STAT_H_DONG_022)
0,6617,2954,2159,1352,1384,662
1,11073,1964,1177,464,2150,1611
2,8225,557,1620,1237,386,856

In [122]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

scaler.fit_transform(저소득)

array([[0.2709117 , 0.9111811 , 0.57664019, 0.44860853, 0.31149598,
        0.10623614],
       [0.57567882, 0.59937008, 0.28773169, 0.11910946, 0.50376506,
        0.34015282],
       [0.3808905 , 0.15622047, 0.41806414, 0.40593692, 0.06099398,
        0.15405472],
       [0.64352643, 0.5376378 , 0.48161224, 0.1974026 , 0.45858434,
        0.17574562],
       [0.34525682, 0.32724409, 0.4012945 , 0.11205937, 0.46536145,
        0.04683263],
       [0.35154914, 1.        , 0.08002354, 0.51280148, 0.45205823,
        0.54720237],
       [0.3966213 , 0.38992126, 0.62606649, 0.71688312, 0.29091365,
        0.33300468],
       [0.51549142, 0.16850394, 0.49867608, 0.31020408, 0.34136546,
        0.43086024],
       [0.39422748, 0.25165354, 0.86084142, 0.56734694, 0.        ,
        0.19423219],
       [0.30408317, 0.42362205, 0.19888202, 0.57922078, 0.33433735,
        0.3921617 ],
       [0.31653102, 0.31244094, 1.        , 0.33729128, 0.4063755 ,
        0.79073207],
       [0.        , 0.30897638, 0.43924684, 0.78330241, 0.19929719,
        0.00419029],
       [0.45797141, 0.27968504, 0.21888791, 1.        , 0.42771084,
        0.09884151],
       [1.        , 0.57291339, 0.40982642, 0.46233766, 0.34964859,
        0.18585161],
       [0.58860543, 0.85732283, 0.        , 0.38961039, 0.22238956,
        0.        ],
       [0.29779085, 0.16125984, 0.69402766, 0.2987013 , 0.28087349,
        0.1404979 ],
       [0.36714315, 0.50173228, 0.72580171, 0.83970315, 0.11320281,
        0.21444417],
       [0.5392928 , 0.85511811, 0.09326272, 0.72987013, 0.11596386,
        0.79023909],
       [0.40366596, 0.8623622 , 0.44924978, 0.43599258, 0.52535141,
        0.09785556],
       [0.04698721, 0.21606299, 0.25536923, 0.35398887, 0.30848394,
        0.12694109],
       [0.1714657 , 0.58299213, 0.08884966, 0.71502783, 1.        ,
        0.24722702],
       [0.35640517, 0.37669291, 0.2886143 , 0.50909091, 0.65261044,
        0.17106236],
       [0.09835169, 0.50929134, 0.07472786, 0.92912801, 0.37248996,
        0.0951442 ],
       [0.37678681, 0.7688189 , 0.50956164, 0.67717996, 0.22188755,
        1.        ],
       [0.41549826, 0.43905512, 0.42365402, 0.74730983, 0.50778112,
        0.22652206],
       [0.25155598, 0.56629921, 0.46278317, 0.        , 0.64257028,
        0.32018733],
       [0.16818275, 0.52755906, 0.15092674, 0.84230056, 0.4249498 ,
        0.52156766],
       [0.68524725, 0.43622047, 0.21447485, 0.9825603 , 0.36822289,
        0.18240079],
       [0.10129266, 0.        , 0.50661959, 0.45009276, 0.64332329,
        0.18190781],
       [0.45879215, 0.60724409, 0.57163872, 0.45602968, 0.35416667,
        0.17796401]])