In [157]:
import pandas as pd
import openpyxl
import numpy as np
import math

# Data Processing

In [136]:
df = pd.read_csv('LOCAL_PEOPLE_DONG_202209.csv', encoding='cp949')
df

           기준일ID  시간대구분    행정기관코드   총생활인구수
0       20220901      0  11350624 17102.82
1       20220901      0  11320690 21759.94
2       20220901      0  11380560 29031.65
3       20220901      0  11110570  7564.08
4       20220901      0  11710566 15097.51
...          ...    ...       ...      ...
305275  20220930     23  11110530 15211.07
305276  20220930     23  11380632 13892.12
305277  20220930     23  11320690 22103.91
305278  20220930     23  11260565 28511.98
305279  20220930     23  11260570 19095.73

[305280 rows x 4 columns]

In [176]:
df['행정기관코드'].nunique()

424

In [106]:
df2 = pd.read_csv('한국행정구역분류_정제.csv', encoding='cp949')
df2

        시도  시군구  행정구역명    행정동      행정기관코드    행정동코드
0    서울특별시  종로구  청운효자동  청운효자동  1111051500  1101072
1    서울특별시  종로구    사직동    사직동  1111053000  1101053
2    서울특별시  종로구    삼청동    삼청동  1111054000  1101054
3    서울특별시  종로구    부암동    부암동  1111055000  1101055
4    서울특별시  종로구    평창동    평창동  1111056000  1101056
..     ...  ...    ...    ...         ...      ...
421  서울특별시  강동구   성내2동  성내제2동  1174065000  1125066
422  서울특별시  강동구   성내3동  성내제3동  1174066000  1125067
423  서울특별시  강동구     길동     길동  1174068500  1125074
424  서울특별시  강동구   둔촌1동  둔촌제1동  1174069000  1125070
425  서울특별시  강동구   둔촌2동  둔촌제2동  1174070000  1125071

[426 rows x 6 columns]

In [118]:
df2['행정기관코드_전처리'] = (df2['행정기관코드']/100).astype(np.int64)
#df['컬럼명'].map(lambda x:x[:-2])
df2

        시도  시군구  행정구역명    행정동      행정기관코드    행정동코드  행정기관코드_전처리
0    서울특별시  종로구  청운효자동  청운효자동  1111051500  1101072    11110515
1    서울특별시  종로구    사직동    사직동  1111053000  1101053    11110530
2    서울특별시  종로구    삼청동    삼청동  1111054000  1101054    11110540
3    서울특별시  종로구    부암동    부암동  1111055000  1101055    11110550
4    서울특별시  종로구    평창동    평창동  1111056000  1101056    11110560
..     ...  ...    ...    ...         ...      ...         ...
421  서울특별시  강동구   성내2동  성내제2동  1174065000  1125066    11740650
422  서울특별시  강동구   성내3동  성내제3동  1174066000  1125067    11740660
423  서울특별시  강동구     길동     길동  1174068500  1125074    11740685
424  서울특별시  강동구   둔촌1동  둔촌제1동  1174069000  1125070    11740690
425  서울특별시  강동구   둔촌2동  둔촌제2동  1174070000  1125071    11740700

[426 rows x 7 columns]

In [123]:
df2.to_csv('행정동_기관코드_전처리.csv')

In [132]:
df2 = pd.read_csv('행정동_기관코드_전처리.csv', encoding='cp949')
df2

        시도  시군구    행정동    행정동코드    행정기관코드
0    서울특별시  종로구  청운효자동  1101072  11110515
1    서울특별시  종로구    사직동  1101053  11110530
2    서울특별시  종로구    삼청동  1101054  11110540
3    서울특별시  종로구    부암동  1101055  11110550
4    서울특별시  종로구    평창동  1101056  11110560
..     ...  ...    ...      ...       ...
421  서울특별시  강동구  성내제2동  1125066  11740650
422  서울특별시  강동구  성내제3동  1125067  11740660
423  서울특별시  강동구     길동  1125074  11740685
424  서울특별시  강동구  둔촌제1동  1125070  11740690
425  서울특별시  강동구  둔촌제2동  1125071  11740700

[426 rows x 5 columns]

In [173]:
df2['행정기관코드'].nunique()

426

In [137]:
df = df.round({'총생활인구수':0})

In [170]:
df

           기준일ID  시간대구분    행정기관코드   총생활인구수
0       20220901      0  11350624 17103.00
1       20220901      0  11320690 21760.00
2       20220901      0  11380560 29032.00
3       20220901      0  11110570  7564.00
4       20220901      0  11710566 15098.00
...          ...    ...       ...      ...
305275  20220930     23  11110530 15211.00
305276  20220930     23  11380632 13892.00
305277  20220930     23  11320690 22104.00
305278  20220930     23  11260565 28512.00
305279  20220930     23  11260570 19096.00

[305280 rows x 4 columns]

In [171]:
df['행정기관코드'].nunique()

424

In [142]:
df3 = pd.merge(df,df2,on='행정기관코드',how='left')
#그리고 새로운 데이터프레임에 씌우기
df3

           기준일ID  시간대구분    행정기관코드   총생활인구수     시도  시군구    행정동      행정동코드
0       20220901      0  11350624 17103.00  서울특별시  노원구   중계4동 1111064.00
1       20220901      0  11320690 21760.00  서울특별시  도봉구  방학제1동 1110055.00
2       20220901      0  11380560 29032.00  서울특별시  은평구    구산동 1112057.00
3       20220901      0  11110570  7564.00  서울특별시  종로구    무악동 1101057.00
4       20220901      0  11710566 15098.00  서울특별시  송파구    오륜동 1124059.00
...          ...    ...       ...      ...    ...  ...    ...        ...
305275  20220930     23  11110530 15211.00  서울특별시  종로구    사직동 1101053.00
305276  20220930     23  11380632 13892.00  서울특별시  은평구  신사제2동 1112066.00
305277  20220930     23  11320690 22104.00  서울특별시  도봉구  방학제1동 1110055.00
305278  20220930     23  11260565 28512.00  서울특별시  중랑구   면목본동 1107071.00
305279  20220930     23  11260570 19096.00  서울특별시  중랑구  면목제7동 1107057.00

[305280 rows x 8 columns]

In [161]:
df3.isnull().sum()

기준일ID        0
시간대구분        0
행정기관코드       0
총생활인구수       0
시도        5040
시군구       5040
행정동       5040
행정동코드     5040
dtype: int64

In [168]:
df3['행정기관코드'].nunique()

424

In [174]:
df3['행정동'].nunique()

416

In [151]:
#행정동코드에 소숫점 2자리 없애기
df3.dtypes

기준일ID       int64
시간대구분       int64
행정기관코드      int64
총생활인구수    float64
시도         object
시군구        object
행정동        object
행정동코드     float64
dtype: object

In [159]:
df3['행정동코드'] = df3['행정동코드'].astype(int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [7]:
df3 = pd.merge(df,df2,on='행정동코드',how='left')

In [8]:
df3

           기준일ID  시간대구분     행정동코드   총생활인구수    시도명 시군구명   읍면동명
0       20220901      0  11350624  17103.0  서울특별시  노원구   중계4동
1       20220901      0  11320690  21760.0  서울특별시  도봉구  방학제1동
2       20220901      0  11380560  29032.0  서울특별시  은평구    구산동
3       20220901      0  11110570   7564.0  서울특별시  종로구    무악동
4       20220901      0  11710566  15098.0  서울특별시  송파구    오륜동
...          ...    ...       ...      ...    ...  ...    ...
305275  20220930     23  11110530  15211.0  서울특별시  종로구    사직동
305276  20220930     23  11380632  13892.0  서울특별시  은평구  신사제2동
305277  20220930     23  11320690  22104.0  서울특별시  도봉구  방학제1동
305278  20220930     23  11260565  28512.0  서울특별시  중랑구   면목본동
305279  20220930     23  11260570  19096.0  서울특별시  중랑구  면목제7동

[305280 rows x 7 columns]

In [9]:
df3.isnull().sum()

기준일ID     0
시간대구분     0
행정동코드     0
총생활인구수    0
시도명       0
시군구명      0
읍면동명      0
dtype: int64

# 최종데이터 전처리 다시하기

In [101]:
원본 = pd.read_csv('행정동별_평균생활인구수.csv', encoding='cp949')
원본

     Unnamed: 0 시군구명      행정기관코드    행정동코드   읍면동명  행정동별_평균생활인구수         주소
0             0  종로구  1111051500  1101072  청운효자동      21903.87  종로구 청운효자동
1             1  종로구  1111053000  1101053    사직동      36892.80    종로구 사직동
2             2  종로구  1111054000  1101054    삼청동       7484.26    종로구 삼청동
3             3  종로구  1111055000  1101055    부암동      14885.11    종로구 부암동
4             4  종로구  1111056000  1101056    평창동      17153.10    종로구 평창동
..          ...  ...         ...      ...    ...           ...        ...
421         421  강동구  1174065000  1125066  성내제2동      22255.83  강동구 성내제2동
422         422  강동구  1174066000  1125067  성내제3동      24714.57  강동구 성내제3동
423         423  강동구  1174068500  1125074     길동      52815.29     강동구 길동
424         424  강동구  1174069000  1125070  둔촌제1동       4126.79  강동구 둔촌제1동
425         425  강동구  1174070000  1125071  둔촌제2동      26198.55  강동구 둔촌제2동

[426 rows x 7 columns]

In [100]:
원본.isnull().sum()

Unnamed: 0      0
행정동코드           0
시군구명            0
행정기관코드          0
행정동코드.1         0
읍면동명            0
행정동별_평균생활인구수    0
주소              0
dtype: int64

## 주간평균

In [15]:
df4 = df3[(df3['시간대구분'] <= 18)]

In [16]:
df4

           기준일ID  시간대구분     행정동코드   총생활인구수    시도명  시군구명    읍면동명
0       20220901      0  11350624  17103.0  서울특별시   노원구    중계4동
1       20220901      0  11320690  21760.0  서울특별시   도봉구   방학제1동
2       20220901      0  11380560  29032.0  서울특별시   은평구     구산동
3       20220901      0  11110570   7564.0  서울특별시   종로구     무악동
4       20220901      0  11710566  15098.0  서울특별시   송파구     오륜동
...          ...    ...       ...      ...    ...   ...     ...
303155  20220930     18  11140680   9513.0  서울특별시    중구     중림동
303156  20220930     18  11170560  21441.0  서울특별시   용산구  원효로제1동
303157  20220930     18  11140540  33462.0  서울특별시    중구     회현동
303158  20220930     18  11230536  40982.0  서울특별시  동대문구     용신동
303159  20220930     18  11140670  12470.0  서울특별시    중구     황학동

[241680 rows x 7 columns]

In [17]:
주간 = df4[(df4['시간대구분'] >= 9)]

In [18]:
주간

           기준일ID  시간대구분     행정동코드   총생활인구수    시도명  시군구명    읍면동명
3816    20220901      9  11305610  15999.0  서울특별시   강북구   수유제1동
3817    20220901      9  11290760  17815.0  서울특별시   성북구   장위제1동
3818    20220901      9  11305630  25435.0  서울특별시   강북구   수유제3동
3819    20220901      9  11680531  60998.0  서울특별시   강남구    논현2동
3820    20220901      9  11140650   7825.0  서울특별시    중구   신당제5동
...          ...    ...       ...      ...    ...   ...     ...
303155  20220930     18  11140680   9513.0  서울특별시    중구     중림동
303156  20220930     18  11170560  21441.0  서울특별시   용산구  원효로제1동
303157  20220930     18  11140540  33462.0  서울특별시    중구     회현동
303158  20220930     18  11230536  40982.0  서울특별시  동대문구     용신동
303159  20220930     18  11140670  12470.0  서울특별시    중구     황학동

[127200 rows x 7 columns]

In [19]:
주간원본 = 주간.copy()

In [20]:
주간['평균'] = 주간['총생활인구수'].mean()

C:\Users\user\AppData\Local\Temp\ipykernel_13416\1677776286.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  주간['평균'] = 주간['총생활인구수'].mean()

In [21]:
주간

           기준일ID  시간대구분     행정동코드   총생활인구수    시도명  시군구명    읍면동명            평균
3816    20220901      9  11305610  15999.0  서울특별시   강북구   수유제1동  24544.087846
3817    20220901      9  11290760  17815.0  서울특별시   성북구   장위제1동  24544.087846
3818    20220901      9  11305630  25435.0  서울특별시   강북구   수유제3동  24544.087846
3819    20220901      9  11680531  60998.0  서울특별시   강남구    논현2동  24544.087846
3820    20220901      9  11140650   7825.0  서울특별시    중구   신당제5동  24544.087846
...          ...    ...       ...      ...    ...   ...     ...           ...
303155  20220930     18  11140680   9513.0  서울특별시    중구     중림동  24544.087846
303156  20220930     18  11170560  21441.0  서울특별시   용산구  원효로제1동  24544.087846
303157  20220930     18  11140540  33462.0  서울특별시    중구     회현동  24544.087846
303158  20220930     18  11230536  40982.0  서울특별시  동대문구     용신동  24544.087846
303159  20220930     18  11140670  12470.0  서울특별시    중구     황학동  24544.087846

[127200 rows x 8 columns]

In [22]:
주간.평균 = 주간.평균.round()

C:\Users\user\AppData\Local\Temp\ipykernel_13416\593715632.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  주간.평균 = 주간.평균.round()

In [23]:
주간

           기준일ID  시간대구분     행정동코드   총생활인구수    시도명  시군구명    읍면동명       평균
3816    20220901      9  11305610  15999.0  서울특별시   강북구   수유제1동  24544.0
3817    20220901      9  11290760  17815.0  서울특별시   성북구   장위제1동  24544.0
3818    20220901      9  11305630  25435.0  서울특별시   강북구   수유제3동  24544.0
3819    20220901      9  11680531  60998.0  서울특별시   강남구    논현2동  24544.0
3820    20220901      9  11140650   7825.0  서울특별시    중구   신당제5동  24544.0
...          ...    ...       ...      ...    ...   ...     ...      ...
303155  20220930     18  11140680   9513.0  서울특별시    중구     중림동  24544.0
303156  20220930     18  11170560  21441.0  서울특별시   용산구  원효로제1동  24544.0
303157  20220930     18  11140540  33462.0  서울특별시    중구     회현동  24544.0
303158  20220930     18  11230536  40982.0  서울특별시  동대문구     용신동  24544.0
303159  20220930     18  11140670  12470.0  서울특별시    중구     황학동  24544.0

[127200 rows x 8 columns]

## 야간 평균

In [24]:
df3

           기준일ID  시간대구분     행정동코드   총생활인구수    시도명 시군구명   읍면동명
0       20220901      0  11350624  17103.0  서울특별시  노원구   중계4동
1       20220901      0  11320690  21760.0  서울특별시  도봉구  방학제1동
2       20220901      0  11380560  29032.0  서울특별시  은평구    구산동
3       20220901      0  11110570   7564.0  서울특별시  종로구    무악동
4       20220901      0  11710566  15098.0  서울특별시  송파구    오륜동
...          ...    ...       ...      ...    ...  ...    ...
305275  20220930     23  11110530  15211.0  서울특별시  종로구    사직동
305276  20220930     23  11380632  13892.0  서울특별시  은평구  신사제2동
305277  20220930     23  11320690  22104.0  서울특별시  도봉구  방학제1동
305278  20220930     23  11260565  28512.0  서울특별시  중랑구   면목본동
305279  20220930     23  11260570  19096.0  서울특별시  중랑구  면목제7동

[305280 rows x 7 columns]

In [25]:
df5 = df3[(df3['시간대구분'] <= 8)]
df5

           기준일ID  시간대구분     행정동코드   총생활인구수    시도명 시군구명   읍면동명
0       20220901      0  11350624  17103.0  서울특별시  노원구   중계4동
1       20220901      0  11320690  21760.0  서울특별시  도봉구  방학제1동
2       20220901      0  11380560  29032.0  서울특별시  은평구    구산동
3       20220901      0  11110570   7564.0  서울특별시  종로구    무악동
4       20220901      0  11710566  15098.0  서울특별시  송파구    오륜동
...          ...    ...       ...      ...    ...  ...    ...
298915  20220930      8  11140580  14875.0  서울특별시   중구    장충동
298916  20220930      8  11140680  10204.0  서울특별시   중구    중림동
298917  20220930      8  11140570  16210.0  서울특별시   중구     필동
298918  20220930      8  11140550  59051.0  서울특별시   중구     명동
298919  20220930      8  11140605  28469.0  서울특별시   중구   을지로동

[114480 rows x 7 columns]

In [26]:
df6 = df3[(df3['시간대구분'] >= 19)]
df6

           기준일ID  시간대구분     행정동코드   총생활인구수    시도명 시군구명   읍면동명
8056    20220901     19  11740620  27018.0  서울특별시  강동구  천호제3동
8057    20220901     19  11440590  30894.0  서울특별시  마포구    용강동
8058    20220901     19  11170580   9681.0  서울특별시  용산구    효창동
8059    20220901     19  11500591  18935.0  서울특별시  강서구  화곡제6동
8060    20220901     19  11440660  98952.0  서울특별시  마포구    서교동
...          ...    ...       ...      ...    ...  ...    ...
305275  20220930     23  11110530  15211.0  서울특별시  종로구    사직동
305276  20220930     23  11380632  13892.0  서울특별시  은평구  신사제2동
305277  20220930     23  11320690  22104.0  서울특별시  도봉구  방학제1동
305278  20220930     23  11260565  28512.0  서울특별시  중랑구   면목본동
305279  20220930     23  11260570  19096.0  서울특별시  중랑구  면목제7동

[63600 rows x 7 columns]

In [27]:
야간 = pd.concat([df5, df6], axis = 0)
야간

           기준일ID  시간대구분     행정동코드   총생활인구수    시도명 시군구명   읍면동명
0       20220901      0  11350624  17103.0  서울특별시  노원구   중계4동
1       20220901      0  11320690  21760.0  서울특별시  도봉구  방학제1동
2       20220901      0  11380560  29032.0  서울특별시  은평구    구산동
3       20220901      0  11110570   7564.0  서울특별시  종로구    무악동
4       20220901      0  11710566  15098.0  서울특별시  송파구    오륜동
...          ...    ...       ...      ...    ...  ...    ...
305275  20220930     23  11110530  15211.0  서울특별시  종로구    사직동
305276  20220930     23  11380632  13892.0  서울특별시  은평구  신사제2동
305277  20220930     23  11320690  22104.0  서울특별시  도봉구  방학제1동
305278  20220930     23  11260565  28512.0  서울특별시  중랑구   면목본동
305279  20220930     23  11260570  19096.0  서울특별시  중랑구  면목제7동

[178080 rows x 7 columns]

In [28]:
야간원본 = 야간.copy()

In [29]:
주간['시간대구분'].unique()

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18], dtype=int64)

In [30]:
야간['시간대구분'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 19, 20, 21, 22, 23],
      dtype=int64)

In [31]:
야간['평균'] = 야간['총생활인구수'].mean()
야간

           기준일ID  시간대구분     행정동코드   총생활인구수    시도명 시군구명   읍면동명            평균
0       20220901      0  11350624  17103.0  서울특별시  노원구   중계4동  23737.766414
1       20220901      0  11320690  21760.0  서울특별시  도봉구  방학제1동  23737.766414
2       20220901      0  11380560  29032.0  서울특별시  은평구    구산동  23737.766414
3       20220901      0  11110570   7564.0  서울특별시  종로구    무악동  23737.766414
4       20220901      0  11710566  15098.0  서울특별시  송파구    오륜동  23737.766414
...          ...    ...       ...      ...    ...  ...    ...           ...
305275  20220930     23  11110530  15211.0  서울특별시  종로구    사직동  23737.766414
305276  20220930     23  11380632  13892.0  서울특별시  은평구  신사제2동  23737.766414
305277  20220930     23  11320690  22104.0  서울특별시  도봉구  방학제1동  23737.766414
305278  20220930     23  11260565  28512.0  서울특별시  중랑구   면목본동  23737.766414
305279  20220930     23  11260570  19096.0  서울특별시  중랑구  면목제7동  23737.766414

[178080 rows x 8 columns]

In [32]:
야간.평균 = 야간.평균.round()

In [33]:
야간

           기준일ID  시간대구분     행정동코드   총생활인구수    시도명 시군구명   읍면동명       평균
0       20220901      0  11350624  17103.0  서울특별시  노원구   중계4동  23738.0
1       20220901      0  11320690  21760.0  서울특별시  도봉구  방학제1동  23738.0
2       20220901      0  11380560  29032.0  서울특별시  은평구    구산동  23738.0
3       20220901      0  11110570   7564.0  서울특별시  종로구    무악동  23738.0
4       20220901      0  11710566  15098.0  서울특별시  송파구    오륜동  23738.0
...          ...    ...       ...      ...    ...  ...    ...      ...
305275  20220930     23  11110530  15211.0  서울특별시  종로구    사직동  23738.0
305276  20220930     23  11380632  13892.0  서울특별시  은평구  신사제2동  23738.0
305277  20220930     23  11320690  22104.0  서울특별시  도봉구  방학제1동  23738.0
305278  20220930     23  11260565  28512.0  서울특별시  중랑구   면목본동  23738.0
305279  20220930     23  11260570  19096.0  서울특별시  중랑구  면목제7동  23738.0

[178080 rows x 8 columns]

In [34]:
주간.to_csv('주간평균.csv')

In [35]:
야간.to_csv('야간평균.csv')

# 동별 평균 생활인구수

In [36]:
import matplotlib.pyplot as plt
import seaborn as sns
plt.rcParams['font.family'] = 'NanumGothic'

In [37]:
주간['읍면동명'].nunique()

423

In [38]:
야간['읍면동명'].nunique()

423

In [39]:
test = 주간[주간['읍면동명']=='중계4동']

           기준일ID  시간대구분     행정동코드   총생활인구수    시도명 시군구명  읍면동명       평균
3870    20220901      9  11350624  15788.0  서울특별시  노원구  중계4동  24544.0
4256    20220901     10  11350624  15547.0  서울특별시  노원구  중계4동  24544.0
5046    20220901     11  11350624  15786.0  서울특별시  노원구  중계4동  24544.0
5304    20220901     12  11350624  15616.0  서울특별시  노원구  중계4동  24544.0
5538    20220901     13  11350624  15494.0  서울특별시  노원구  중계4동  24544.0
...          ...    ...       ...      ...    ...  ...   ...      ...
301409  20220930     14  11350624  16488.0  서울특별시  노원구  중계4동  24544.0
301818  20220930     15  11350624  15584.0  서울특별시  노원구  중계4동  24544.0
302154  20220930     16  11350624  14438.0  서울특별시  노원구  중계4동  24544.0
302604  20220930     17  11350624  14600.0  서울특별시  노원구  중계4동  24544.0
302996  20220930     18  11350624  15104.0  서울특별시  노원구  중계4동  24544.0

[300 rows x 8 columns]

In [40]:
test['시간대구분'].unique()

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18], dtype=int64)

In [41]:
test2 = 야간[야간['읍면동명']=='중계4동']
test2

           기준일ID  시간대구분     행정동코드   총생활인구수    시도명 시군구명  읍면동명       평균
0       20220901      0  11350624  17103.0  서울특별시  노원구  중계4동  23738.0
654     20220901      1  11350624  17030.0  서울특별시  노원구  중계4동  23738.0
1239    20220901      2  11350624  16948.0  서울특별시  노원구  중계4동  23738.0
1338    20220901      3  11350624  17001.0  서울특별시  노원구  중계4동  23738.0
2009    20220901      4  11350624  16935.0  서울특별시  노원구  중계4동  23738.0
...          ...    ...       ...      ...    ...  ...   ...      ...
303465  20220930     19  11350624  15865.0  서울특별시  노원구  중계4동  23738.0
303953  20220930     20  11350624  15918.0  서울특별시  노원구  중계4동  23738.0
304113  20220930     21  11350624  16350.0  서울특별시  노원구  중계4동  23738.0
304548  20220930     22  11350624  16506.0  서울특별시  노원구  중계4동  23738.0
304900  20220930     23  11350624  16829.0  서울특별시  노원구  중계4동  23738.0

[420 rows x 8 columns]

In [42]:
test2['시간대구분'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 19, 20, 21, 22, 23],
      dtype=int64)

In [43]:
주간원본

           기준일ID  시간대구분     행정동코드   총생활인구수    시도명  시군구명    읍면동명
3816    20220901      9  11305610  15999.0  서울특별시   강북구   수유제1동
3817    20220901      9  11290760  17815.0  서울특별시   성북구   장위제1동
3818    20220901      9  11305630  25435.0  서울특별시   강북구   수유제3동
3819    20220901      9  11680531  60998.0  서울특별시   강남구    논현2동
3820    20220901      9  11140650   7825.0  서울특별시    중구   신당제5동
...          ...    ...       ...      ...    ...   ...     ...
303155  20220930     18  11140680   9513.0  서울특별시    중구     중림동
303156  20220930     18  11170560  21441.0  서울특별시   용산구  원효로제1동
303157  20220930     18  11140540  33462.0  서울특별시    중구     회현동
303158  20220930     18  11230536  40982.0  서울특별시  동대문구     용신동
303159  20220930     18  11140670  12470.0  서울특별시    중구     황학동

[127200 rows x 7 columns]

In [44]:
test3 = 주간원본[주간원본['읍면동명']=='중계4동']
test3

           기준일ID  시간대구분     행정동코드   총생활인구수    시도명 시군구명  읍면동명
3870    20220901      9  11350624  15788.0  서울특별시  노원구  중계4동
4256    20220901     10  11350624  15547.0  서울특별시  노원구  중계4동
5046    20220901     11  11350624  15786.0  서울특별시  노원구  중계4동
5304    20220901     12  11350624  15616.0  서울특별시  노원구  중계4동
5538    20220901     13  11350624  15494.0  서울특별시  노원구  중계4동
...          ...    ...       ...      ...    ...  ...   ...
301409  20220930     14  11350624  16488.0  서울특별시  노원구  중계4동
301818  20220930     15  11350624  15584.0  서울특별시  노원구  중계4동
302154  20220930     16  11350624  14438.0  서울특별시  노원구  중계4동
302604  20220930     17  11350624  14600.0  서울특별시  노원구  중계4동
302996  20220930     18  11350624  15104.0  서울특별시  노원구  중계4동

[300 rows x 7 columns]

In [45]:
test3['주간평균'] = test3['총생활인구수'].mean()
test3

C:\Users\user\AppData\Local\Temp\ipykernel_13416\3099345734.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3['주간평균'] = test3['총생활인구수'].mean()

           기준일ID  시간대구분     행정동코드   총생활인구수    시도명 시군구명  읍면동명      주간평균
3870    20220901      9  11350624  15788.0  서울특별시  노원구  중계4동  15170.26
4256    20220901     10  11350624  15547.0  서울특별시  노원구  중계4동  15170.26
5046    20220901     11  11350624  15786.0  서울특별시  노원구  중계4동  15170.26
5304    20220901     12  11350624  15616.0  서울특별시  노원구  중계4동  15170.26
5538    20220901     13  11350624  15494.0  서울특별시  노원구  중계4동  15170.26
...          ...    ...       ...      ...    ...  ...   ...       ...
301409  20220930     14  11350624  16488.0  서울특별시  노원구  중계4동  15170.26
301818  20220930     15  11350624  15584.0  서울특별시  노원구  중계4동  15170.26
302154  20220930     16  11350624  14438.0  서울특별시  노원구  중계4동  15170.26
302604  20220930     17  11350624  14600.0  서울특별시  노원구  중계4동  15170.26
302996  20220930     18  11350624  15104.0  서울특별시  노원구  중계4동  15170.26

[300 rows x 8 columns]

In [46]:
야간원본

           기준일ID  시간대구분     행정동코드   총생활인구수    시도명 시군구명   읍면동명
0       20220901      0  11350624  17103.0  서울특별시  노원구   중계4동
1       20220901      0  11320690  21760.0  서울특별시  도봉구  방학제1동
2       20220901      0  11380560  29032.0  서울특별시  은평구    구산동
3       20220901      0  11110570   7564.0  서울특별시  종로구    무악동
4       20220901      0  11710566  15098.0  서울특별시  송파구    오륜동
...          ...    ...       ...      ...    ...  ...    ...
305275  20220930     23  11110530  15211.0  서울특별시  종로구    사직동
305276  20220930     23  11380632  13892.0  서울특별시  은평구  신사제2동
305277  20220930     23  11320690  22104.0  서울특별시  도봉구  방학제1동
305278  20220930     23  11260565  28512.0  서울특별시  중랑구   면목본동
305279  20220930     23  11260570  19096.0  서울특별시  중랑구  면목제7동

[178080 rows x 7 columns]

In [47]:
pd.options.display.float_format = '{:.2f}'.format

주간 = 주간원본[['행정동코드','시군구명','읍면동명','총생활인구수']]
mean_주간 = pd.DataFrame(주간.groupby(['행정동코드','시군구명','읍면동명']).agg({'총생활인구수':"mean"}).rename(columns={'총생활인구수':'행정동별_평균생활인구수'})).reset_index()
mean_주간

        행정동코드 시군구명   읍면동명  행정동별_평균생활인구수
0    11110515  종로구  청운효자동      21903.87
1    11110530  종로구    사직동      36892.80
2    11110540  종로구    삼청동       7484.26
3    11110550  종로구    부암동      14885.11
4    11110560  종로구    평창동      17153.10
..        ...  ...    ...           ...
419  11740650  강동구  성내제2동      22255.83
420  11740660  강동구  성내제3동      24714.57
421  11740685  강동구     길동      52815.29
422  11740690  강동구  둔촌제1동       4126.79
423  11740700  강동구  둔촌제2동      26198.55

[424 rows x 4 columns]

In [48]:
mean_주간['주소']=mean_주간['시군구명']+str(' ')+mean_주간['읍면동명']
mean_주간

        행정동코드 시군구명   읍면동명  행정동별_평균생활인구수         주소
0    11110515  종로구  청운효자동      21903.87  종로구 청운효자동
1    11110530  종로구    사직동      36892.80    종로구 사직동
2    11110540  종로구    삼청동       7484.26    종로구 삼청동
3    11110550  종로구    부암동      14885.11    종로구 부암동
4    11110560  종로구    평창동      17153.10    종로구 평창동
..        ...  ...    ...           ...        ...
419  11740650  강동구  성내제2동      22255.83  강동구 성내제2동
420  11740660  강동구  성내제3동      24714.57  강동구 성내제3동
421  11740685  강동구     길동      52815.29     강동구 길동
422  11740690  강동구  둔촌제1동       4126.79  강동구 둔촌제1동
423  11740700  강동구  둔촌제2동      26198.55  강동구 둔촌제2동

[424 rows x 5 columns]

In [49]:
mean_주간.to_csv('행정동별_평균생활인구수(주간).csv')

In [50]:
야간 = 야간원본[['행정동코드','시군구명','읍면동명','총생활인구수']]
mean_야간 = pd.DataFrame(야간.groupby(['행정동코드','시군구명','읍면동명']).agg({'총생활인구수':"mean"}).rename(columns={'총생활인구수':'행정동별_평균생활인구수'})).reset_index()
mean_야간

        행정동코드 시군구명   읍면동명  행정동별_평균생활인구수
0    11110515  종로구  청운효자동      15653.87
1    11110530  종로구    사직동      17266.70
2    11110540  종로구    삼청동       3700.41
3    11110550  종로구    부암동      14555.74
4    11110560  종로구    평창동      18799.65
..        ...  ...    ...           ...
419  11740650  강동구  성내제2동      25465.33
420  11740660  강동구  성내제3동      27100.14
421  11740685  강동구     길동      55390.45
422  11740690  강동구  둔촌제1동       4671.77
423  11740700  강동구  둔촌제2동      27821.13

[424 rows x 4 columns]

In [51]:
mean_야간['주소']=mean_야간['시군구명']+str(' ')+mean_야간['읍면동명']
mean_야간

        행정동코드 시군구명   읍면동명  행정동별_평균생활인구수         주소
0    11110515  종로구  청운효자동      15653.87  종로구 청운효자동
1    11110530  종로구    사직동      17266.70    종로구 사직동
2    11110540  종로구    삼청동       3700.41    종로구 삼청동
3    11110550  종로구    부암동      14555.74    종로구 부암동
4    11110560  종로구    평창동      18799.65    종로구 평창동
..        ...  ...    ...           ...        ...
419  11740650  강동구  성내제2동      25465.33  강동구 성내제2동
420  11740660  강동구  성내제3동      27100.14  강동구 성내제3동
421  11740685  강동구     길동      55390.45     강동구 길동
422  11740690  강동구  둔촌제1동       4671.77  강동구 둔촌제1동
423  11740700  강동구  둔촌제2동      27821.13  강동구 둔촌제2동

[424 rows x 5 columns]

In [52]:
mean_야간.to_csv('행정동별_평균생활인구수(야간).csv')

# 위경도 추가하기

In [53]:
from geopy.geocoders import Nominatim
geo_local = Nominatim(user_agent='South Korea')

In [102]:
def geocoding(address):
    try:
        geo = geo_local.geocode(address)
        x_y = [geo.latitude, geo.longitude]
        return x_y

    except:
        return [0,0]

In [103]:
latitude = []
longitude =[]

for i in mean_주간['주소']:
    latitude.append(geocoding(i)[0])
    longitude.append(geocoding(i)[1])

In [104]:
address_주간 = pd.DataFrame({'상세주소':mean_주간['주소'],'위도':latitude,'경도':longitude, '행정동별_평균생활인구수':mean_주간['행정동별_평균생활인구수']})

In [105]:
address_주간

          상세주소    위도     경도  행정동별_평균생활인구수
0    종로구 청운효자동 37.58 126.97      21903.87
1      종로구 사직동 37.58 126.97      36892.80
2      종로구 삼청동 37.59 126.98       7484.26
3      종로구 부암동 37.59 126.97      14885.11
4      종로구 평창동 37.61 126.97      17153.10
..         ...   ...    ...           ...
419  강동구 성내제2동  0.00   0.00      22255.83
420  강동구 성내제3동  0.00   0.00      24714.57
421     강동구 길동 37.54 127.14      52815.29
422  강동구 둔촌제1동  0.00   0.00       4126.79
423  강동구 둔촌제2동  0.00   0.00      26198.55

[424 rows x 4 columns]

In [58]:
address_주간.to_csv('주소_행정동별_평균생활인구수(주간).csv')

In [ ]:
latitude = []
longitude =[]

for i in mean_야간['주소']:
    latitude.append(geocoding(i)[0])
    longitude.append(geocoding(i)[1])

In [ ]:
address_야간 = pd.DataFrame({'상세주소':mean_야간['주소'],'위도':latitude,'경도':longitude, '행정동별_평균생활인구수':mean_야간['행정동별_평균생활인구수']})

In [ ]:
address_야간

# 주간야간 합쳐서 총 평균구하기

In [2]:
import pandas as pd
import numpy as np

In [4]:
주간 = pd.read_csv('행정동_평균생활인구수(주간).csv', encoding='cp949')
주간

            주소  시군구 행정구역명(원본)    행정기관코드    행정동코드  행정동별_평균생활인구수
0    종로구 청운효자동  종로구     청운효자동  11110515  1101072  21903.873330
1      종로구 사직동  종로구       사직동  11110530  1101053  36892.796670
2      종로구 삼청동  종로구       삼청동  11110540  1101054   7484.263333
3      종로구 부암동  종로구       부암동  11110550  1101055  14885.106670
4      종로구 평창동  종로구       평창동  11110560  1101056  17153.096670
..         ...  ...       ...       ...      ...           ...
421  강동구 성내제2동  강동구      성내2동  11740650  1125066  22255.830000
422  강동구 성내제3동  강동구      성내3동  11740660  1125067  24714.570000
423     강동구 길동  강동구        길동  11740685  1125074  52815.293330
424  강동구 둔촌제1동  강동구      둔촌1동  11740690  1125070   4126.790000
425  강동구 둔촌제2동  강동구      둔촌2동  11740700  1125071  26198.553330

[426 rows x 6 columns]

In [5]:
야간 = pd.read_csv('행정동_평균생활인구수(야간).csv', encoding='cp949')
야간

,주소,시군구,위도,경도,행정구역명(원본),행정기관코드,행정동코드,행정동별_평균생활인구수
0,종로구 청운효자동,종로구,37.584061,126.970580,청운효자동,11110515,1101072,15653.871430
1,종로구 사직동,종로구,37.576164,126.968806,사직동,11110530,1101053,17266.695240
2,종로구 삼청동,종로구,37.584838,126.981913,삼청동,11110540,1101054,3700.411905
3,종로구 부암동,종로구,37.596261,126.967699,부암동,11110550,1101055,14555.738100
4,종로구 평창동,종로구,37.605335,126.966858,평창동,11110560,1101056,18799.654760
...,...,...,...,...,...,...,...,...
421,강동구 성내제2동,강동구,37.530292,127.128765,성내2동,11740650,1125066,25465.333330
422,강동구 성내제3동,강동구,37.525987,127.132900,성내3동,11740660,1125067,27100.140480
423,강동구 길동,강동구,37.539207,127.146121,길동,11740685,1125074,55390.452380
424,강동구 둔촌제1동,강동구,37.527203,127.144105,둔촌1동,11740690,1125070,4671.766667
425,강동구 둔촌제2동,강동구,37.527203,127.144105,둔촌2동,11740700,1125071,27821.133330

In [9]:
total = pd.merge(주간,야간,on='행정동코드',how='left')
total

,주소_x,시군구_x,행정구역명(원본)_x,행정기관코드_x,행정동코드,행정동별_평균생활인구수_x,주소_y,시군구_y,위도,경도,행정구역명(원본)_y,행정기관코드_y,행정동별_평균생활인구수_y
0,종로구 청운효자동,종로구,청운효자동,11110515,1101072,21903.873330,종로구 청운효자동,종로구,37.584061,126.970580,청운효자동,11110515,15653.871430
1,종로구 사직동,종로구,사직동,11110530,1101053,36892.796670,종로구 사직동,종로구,37.576164,126.968806,사직동,11110530,17266.695240
2,종로구 삼청동,종로구,삼청동,11110540,1101054,7484.263333,종로구 삼청동,종로구,37.584838,126.981913,삼청동,11110540,3700.411905
3,종로구 부암동,종로구,부암동,11110550,1101055,14885.106670,종로구 부암동,종로구,37.596261,126.967699,부암동,11110550,14555.738100
4,종로구 평창동,종로구,평창동,11110560,1101056,17153.096670,종로구 평창동,종로구,37.605335,126.966858,평창동,11110560,18799.654760
...,...,...,...,...,...,...,...,...,...,...,...,...,...
421,강동구 성내제2동,강동구,성내2동,11740650,1125066,22255.830000,강동구 성내제2동,강동구,37.530292,127.128765,성내2동,11740650,25465.333330
422,강동구 성내제3동,강동구,성내3동,11740660,1125067,24714.570000,강동구 성내제3동,강동구,37.525987,127.132900,성내3동,11740660,27100.140480
423,강동구 길동,강동구,길동,11740685,1125074,52815.293330,강동구 길동,강동구,37.539207,127.146121,길동,11740685,55390.452380
424,강동구 둔촌제1동,강동구,둔촌1동,11740690,1125070,4126.790000,강동구 둔촌제1동,강동구,37.527203,127.144105,둔촌1동,11740690,4671.766667
425,강동구 둔촌제2동,강동구,둔촌2동,11740700,1125071,26198.553330,강동구 둔촌제2동,강동구,37.527203,127.144105,둔촌2동,11740700,27821.133330

In [10]:
total['행정동별_평균생활인구수_합계'] = total['행정동별_평균생활인구수_x'] + total['행정동별_평균생활인구수_y']

In [11]:
total

,주소_x,시군구_x,행정구역명(원본)_x,행정기관코드_x,행정동코드,행정동별_평균생활인구수_x,주소_y,시군구_y,위도,경도,행정구역명(원본)_y,행정기관코드_y,행정동별_평균생활인구수_y,행정동별_평균생활인구수_합계
0,종로구 청운효자동,종로구,청운효자동,11110515,1101072,21903.873330,종로구 청운효자동,종로구,37.584061,126.970580,청운효자동,11110515,15653.871430,37557.744760
1,종로구 사직동,종로구,사직동,11110530,1101053,36892.796670,종로구 사직동,종로구,37.576164,126.968806,사직동,11110530,17266.695240,54159.491910
2,종로구 삼청동,종로구,삼청동,11110540,1101054,7484.263333,종로구 삼청동,종로구,37.584838,126.981913,삼청동,11110540,3700.411905,11184.675238
3,종로구 부암동,종로구,부암동,11110550,1101055,14885.106670,종로구 부암동,종로구,37.596261,126.967699,부암동,11110550,14555.738100,29440.844770
4,종로구 평창동,종로구,평창동,11110560,1101056,17153.096670,종로구 평창동,종로구,37.605335,126.966858,평창동,11110560,18799.654760,35952.751430
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421,강동구 성내제2동,강동구,성내2동,11740650,1125066,22255.830000,강동구 성내제2동,강동구,37.530292,127.128765,성내2동,11740650,25465.333330,47721.163330
422,강동구 성내제3동,강동구,성내3동,11740660,1125067,24714.570000,강동구 성내제3동,강동구,37.525987,127.132900,성내3동,11740660,27100.140480,51814.710480
423,강동구 길동,강동구,길동,11740685,1125074,52815.293330,강동구 길동,강동구,37.539207,127.146121,길동,11740685,55390.452380,108205.745710
424,강동구 둔촌제1동,강동구,둔촌1동,11740690,1125070,4126.790000,강동구 둔촌제1동,강동구,37.527203,127.144105,둔촌1동,11740690,4671.766667,8798.556667
425,강동구 둔촌제2동,강동구,둔촌2동,11740700,1125071,26198.553330,강동구 둔촌제2동,강동구,37.527203,127.144105,둔촌2동,11740700,27821.133330,54019.686660

In [15]:
total.to_csv('행정동별_평균생활인구수_합계ver.csv')